### ISSUE TITLE
Add airport codes as a phrase part type

### ISSUE THREAD

**Issue by philipmw** [philipmw/phrase.shop#10]
Good list here: https://www.faa.gov/airports/planning_capacity/passenger_allcargo_stats/passenger/media/preliminary-cy19-commercial-service-enplanements.pdf

**Comment by 0xln** [comment]
Think the link is broken above, should be [Enplanements at All Commercial Service Airports](https://www.faa.gov/airports/planning_capacity/passenger_allcargo_stats/passenger/media/cy19-commercial-service-enplanements.pdf). 

So a list of the Locid's from column four ?

**Comment by philipmw** [comment]
Yep, that's the right file and LocIds is what I was thinking. Either all uppercase like state abbreviations, or lowercase would also be fine... you can decide.

**Comment by 0xln** [comment]
Or would you be interested in me sourcing a global list for higher entropy ?

For example like the one collated here
https://github.com/datasets/airport-codes

**Comment by philipmw** [comment]
It's a tradeoff between security (higher entropy) and memorability.

So far, I've been biasing toward memorability, because the internet already has a bunch of password generators that produce meaningless and hard-to-memorize strings. Hence why the _word_ bank is limited to Voice of America vocabulary (just a thousand words), and we have some low-entropy but memorable wordbanks like colors and US state abbreviations. Also, I had to make the decision that the audience of this web site is English speakers and (probably) US residents, so we want to maximize memorability for this audience rather than for the entire world.

Given all that, **my preference would be to stick to US airports.** For a random US airport code, I can probably guess what city and state it's for. But that wouldn't be true if I was given an airport code from a global list.

**Comment by 0xln** [comment]
Thanks for the input. Will focus on the US codes, and PR my fork once its ready.
